skip_tags: true
image: Visual Studio 2017
configuration: Release

skip_commits:
  message: /\[WIP\]/

on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip

install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

after_build:
  - cmd: ECHO nuget pack phirSOFT.SettingsService.ApplicationSettingsService\phirSOFT.SettingsService.ApplicationSettingsService.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack phirSOFT.SettingsService.ApplicationSettingsService\phirSOFT.SettingsService.ApplicationSettingsService.csproj -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "phirSOFT.SettingsService.ApplicationSettingsService.%GitVersion_NuGetVersion%.nupkg"

deploy:
- provider: GitHub
  auth_token:
    secure: yswFCZCA7JeJhx7wgRTYHUrG4ekVIL1HHlzbnx8J5zLALrtBrMEhYf5djORWOFyR
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: hels9jrBxofzs3cwlkKIPfKc/6SY6egULGZsKj6Gxlberu6Cqk1W4PivmhfcnfPS
  on:
    branch: master